name: Deploy release artifacts

on:
  push:
    branches:
      - master
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  deploy:
    if: github.repository_owner == 'zigtools'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # required to resolve the version string

      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: master

      - name: Install 7zip
        run: |
          sudo apt-get update
          sudo apt-get install 7zip

      - run: zig env

      - name: Build artifacts
        run: |
          zig build release -Doptimize=ReleaseSafe -Drelease-compress --summary all

      - uses: ryand56/r2-upload-action@latest
        with:
          r2-account-id: ${{ secrets.R2_ACCOUNT_ID }}
          r2-access-key-id: ${{ secrets.R2_ACCESS_KEY_ID }}
          r2-secret-access-key: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          r2-bucket: ${{ secrets.R2_BUCKET }}
          source-dir: zig-out/artifacts
          destination-dir: builds
